import type { Metadata } from "next";
import "./global.css";
import Nav from "./components/nav";
import Footer from "./components/footer";
import { AuthProvider } from "@/hooks/useContext";
import { verifySession } from "./lib/verifySession";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await verifySession();
  return (
    <html lang="en">
      <body className="bg-(--background)">
        <AuthProvider>
          <header className="mb-(--mg-l) ">
            <Nav username={session?.email} />
          </header>
          {children}
          <footer>
            <Footer />
          </footer>
        </AuthProvider>
      </body>
    </html>
  );
}
