import { verifySession } from "@/app/lib/verifySession";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function CreatePostLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await verifySession();
  if (!session) {
    return (
      <div>
        <p>Please make your login</p>
      </div>
    );
  }
  return <>{children}</>;
}
